name: Deploy Python App to Azure

on:
  push:
    branches:
      - main  # 當 main 分支有推送時觸發

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 檢出程式碼
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 設定 Python 環境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. 安裝依賴套件
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 部署到 Azure
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: <你的 Azure App Service 名稱>  # 替換為你的 App Service 名稱
          slot-name: production
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
